### ISSUE TITLE
problem1.cpp

### ISSUE THREAD

**Issue by skdudn321** [superyodi/AlgorithmStrudy#1]
```
for(int i=0; i<arr.size(); i++) {
        if(arr[i]!=arr[i+1]) {
            answer.push_back(arr[i]);
        }
    }
```

arr[i] != arr[i+1]이면 마지막에(i = arr.size() - 1 일 때)
vector index 범위를 초과하는것 같습니다

**Comment by superyodi** [comment]
오호? 그러게요? 그래서 프로그래머스에서 출력 넣어서 돌려보니까
![image](https://user-images.githubusercontent.com/31922389/55667907-76567c80-589d-11e9-9e7c-4a023467daf5.png) 
![image](https://user-images.githubusercontent.com/31922389/55667915-8c643d00-589d-11e9-8b80-a34cb796996c.png)

이렇게...ㄷㄷ 왜 랜덤 숫자가 나올까여?

**Comment by skdudn321** [comment]
인덱스를 초과한 메모리가 readable하다면 접근해서 읽을 수는 있겠지만,
실제 어떤 값이 들어있을지는 예측할 수 없기 때문에 랜덤값이 나오는 거에요.

**Comment by skdudn321** [comment]
+ 변경한 코드는 프로그래머스 사이트에서 정답이 안나와요!

**Comment by superyodi** [comment]
ㅎㅎㅎ미쳤네요ㅎㅎㅎ
아주 엄청난 실수를 했는데 오류 잡아주셔서 감사합니다 ㅠㅜㅠㅠ
그리워유 프로알고리즈머~!!!!

**Comment by skdudn321** [comment]
오 좋아요 이제 문제 없어보여요!
good~!
